"use client";

import { ChangeEvent, FormEvent, useState } from "react";
import type { Company } from "@/features/companies/types";

export function EmployerCompanyForm({ company }: { company: Company & { logoStorageKey?: string } }) {
  const [logo, setLogo] = useState<File | null>(null);
  const [state, setState] = useState<"idle" | "saving" | "saved">("idle");
  function save(e: FormEvent) { e.preventDefault(); setState("saving"); window.setTimeout(() => setState("saved"), 250); }
  function file(e: ChangeEvent<HTMLInputElement>) { setLogo(e.target.files?.[0] ?? null); }
  return <form onSubmit={save} className="space-y-5"><section className="rounded-card border border-line bg-white p-5 shadow-soft"><h2 className="font-display text-[20px] font-semibold text-ink">Company Basics</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Input label="Company name" defaultValue={company.name} /><Input label="Website" defaultValue={company.website} /><Input label="Industry" defaultValue={company.industry} /><Input label="Company size" defaultValue={company.size} /></div></section><section className="rounded-card border border-line bg-white p-5 shadow-soft"><h2 className="font-display text-[20px] font-semibold text-ink">Brand & Description</h2><label className="mt-4 block text-[13.5px] font-medium text-ink">Logo<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={file} className="mt-2 block w-full rounded-card border border-line bg-white px-3 py-2 text-[14px] file:mr-3 file:rounded-pill file:border-0 file:bg-plum-50 file:px-3 file:py-2 file:text-[13px] file:font-medium file:text-plum-700" /></label><p className="mt-2 text-[13px] text-mist">Selected: {logo?.name ?? company.logoStorageKey ?? "No logo selected"}</p><label className="mt-4 block text-[13.5px] font-medium text-ink">Description<textarea defaultValue={company.description} rows={5} className={`${controlClass} py-2`} /></label></section><section className="rounded-card border border-line bg-white p-5 shadow-soft"><h2 className="font-display text-[20px] font-semibold text-ink">Locations</h2><Input label="Locations" defaultValue={company.locations.join(", ")} /></section>{state === "saved" && <p className="rounded-card bg-plum-50 p-3 text-[13.5px] text-ink/80">Saved in frontend mock state only.</p>}<button disabled={state === "saving"} className="min-h-11 w-full rounded-pill bg-plum-600 px-5 text-[14.5px] font-medium text-white hover:bg-plum-700 disabled:cursor-not-allowed disabled:opacity-70 sm:w-auto">{state === "saving" ? "Saving..." : "Save Company Profile"}</button></form>;
}
const controlClass = "mt-1.5 min-h-11 w-full rounded-card border border-line bg-white px-3 text-[14.5px] text-ink shadow-none transition-colors placeholder:text-mist/65 focus:border-plum-400 focus:outline-none focus:ring-2 focus:ring-plum-200";
function Input({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="text-[13.5px] font-medium text-ink">{label}<input {...props} className={controlClass} /></label>; }
