const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const base = process.env.QA_BASE_URL || "http://localhost:3100";
const output = process.env.QA_OUTPUT || path.join(require("node:os").tmpdir(), "growbiz-ui-qa");
const routes = ["/", "/jobs", "/jobs/backend-engineer-bengaluru-2201", "/employers", "/recruitment-services", "/pricing", "/career-resources", "/campus", "/about", "/contact", "/candidate/dashboard", "/employer/dashboard", "/recruiter", "/admin"];
const widths = [320,360,390,430,768,1024,1280,1440];
(async () => {
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true });
  const page = await browser.newPage();
  const errors = [], checks = [], interactions = {};
  page.on("pageerror", e => errors.push(e.message));
  page.on("console", e => { if (e.type() === "error") errors.push(e.text()); });
  for (const route of routes) {
    const response = await page.goto(base + route);
    await page.waitForLoadState("networkidle");
    assert.equal(response.status(), 200, route);
    const h1 = await page.locator("h1").allTextContents();
    assert.equal(h1.length, 1, route);
    for (const width of widths) {
      await page.setViewportSize({ width, height: 900 });
      const result = await page.evaluate(() => ({
        width: innerWidth, scrollWidth: document.documentElement.scrollWidth,
        overflow: [...document.querySelectorAll("header *, main *")].filter(el => {
          const rect = el.getBoundingClientRect(), style = getComputedStyle(el);
          return rect.width && rect.height && style.display !== "none" && style.visibility !== "hidden" && !el.closest('[aria-hidden="true"]') && (rect.right > innerWidth + 1 || rect.left < -1);
        }).slice(0,5).map(el => ({ tag: el.tagName, text: el.textContent.slice(0,60) })),
      }));
      checks.push({ route, h1: h1[0], ...result });
      if (width === 390 || width === 1440) await page.screenshot({ path: path.join(output, (route === "/" ? "home" : route.slice(1).replaceAll("/", "-")) + `-${width}.png`) });
    }
    console.log(JSON.stringify({ route, overflow: checks.filter(r => r.route === route && (r.overflow.length || r.scrollWidth > r.width)) }));
  }
  await page.goto(base);
  await page.setViewportSize({ width: 1440, height: 900 });
  const primary = page.locator('header .gb-button--primary').first();
  const secondary = page.locator('header .gb-button--secondary').first();
  await primary.hover(); await page.waitForTimeout(280);
  interactions.primary = await primary.evaluate(el => ({ background: getComputedStyle(el).backgroundImage, transform: getComputedStyle(el).transform, sheen: getComputedStyle(el, "::before").opacity }));
  assert.match(interactions.primary.background, /linear-gradient/);
  assert.match(interactions.primary.background, /201, 13, 255/);
  assert.match(interactions.primary.background, /164, 0, 207/);
  assert.equal(interactions.primary.sheen, "1");
  await secondary.hover(); await page.waitForTimeout(280);
  interactions.secondary = await secondary.evaluate(el => ({ background: getComputedStyle(el).backgroundColor, transform: getComputedStyle(el).transform, blur: getComputedStyle(el).backdropFilter }));
  assert.notEqual(interactions.secondary.blur, "none");
  await page.screenshot({ path: path.join(output, "header-hover.png") });
  await page.evaluate(() => window.scrollTo(0, 500));
  await page.waitForTimeout(280);
  assert.equal(await page.locator("header").getAttribute("data-scrolled"), "true");
  interactions.scrolled = await page.locator("header").evaluate(el => getComputedStyle(el).backdropFilter);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Open menu", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Mobile navigation" });
  assert.ok(await dialog.isVisible());
  assert.notEqual(await dialog.evaluate(el => getComputedStyle(el).backdropFilter), "none");
  assert.ok(await page.locator("header").evaluate(el => el.inert));
  await page.keyboard.press("Shift+Tab");
  assert.ok(await dialog.evaluate(el => el.contains(document.activeElement)));
  await page.keyboard.press("Tab");
  assert.ok(await page.getByRole("button", { name: "Close menu", exact: true }).evaluate(el => el === document.activeElement));
  const rect = await dialog.boundingBox();
  assert.ok(rect.x >= 0 && rect.x + rect.width <= 391 && rect.y + rect.height <= 845);
  await page.screenshot({ path: path.join(output, "mobile-menu.png") });
  await page.keyboard.press("Escape");
  assert.ok(await page.getByRole("button", { name: "Open menu", exact: true }).evaluate(el => el === document.activeElement));
  assert.ok(!(await page.locator("header").evaluate(el => el.inert)));
  interactions.headerFocusTrap = true;
  await page.goto(base + "/jobs");
  await page.getByRole("button", { name: /^Filters/ }).click();
  assert.ok(await page.getByRole("dialog", { name: "Job filters" }).isVisible());
  await page.keyboard.press("Shift+Tab");
  assert.ok(await page.getByRole("dialog", { name: "Job filters" }).evaluate(el => el.contains(document.activeElement)));
  await page.keyboard.press("Escape");
  assert.ok(await page.getByRole("button", { name: /^Filters/ }).evaluate(el => el === document.activeElement));
  interactions.filterFocusTrap = true;
  await page.setViewportSize({ width: 1440, height: 900 });
  const card = page.locator(".glass-interactive").first();
  await card.hover(); await page.waitForTimeout(280);
  interactions.card = await card.evaluate(el => ({ transform: getComputedStyle(el).transform, blur: getComputedStyle(el).backdropFilter, title: getComputedStyle(el.querySelector("a")).color }));
  assert.equal(interactions.card.title, "rgb(15, 23, 42)");
  assert.notEqual(interactions.card.blur, "none");
  await page.screenshot({ path: path.join(output, "job-hover.png") });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await card.hover(); await page.waitForTimeout(50);
  assert.equal(await card.evaluate(el => getComputedStyle(el).transform), "none");
  interactions.reducedMotion = true;
  await page.emulateMedia({ reducedMotion: "no-preference" });
  await page.goto(base + "/jobs/backend-engineer-bengaluru-2201");
  await page.getByRole("button", { name: "Report", exact: true }).click();
  const report = page.getByRole("dialog", { name: "Report job" });
  assert.ok(await report.isVisible());
  const reportRect = await report.boundingBox();
  assert.ok(reportRect.width > 400, "Dialog must escape the 330px sticky aside");
  await page.keyboard.press("Shift+Tab");
  assert.ok(await report.evaluate(el => el.contains(document.activeElement)));
  await page.screenshot({ path: path.join(output, "report-dialog.png") });
  await page.keyboard.press("Escape");
  assert.ok(await page.getByRole("button", { name: "Report", exact: true }).evaluate(el => el === document.activeElement));
  interactions.reportFocusTrap = true;
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base + "/candidate/dashboard");
  await page.getByRole("button", { name: "Open workspace menu" }).click();
  const workspace = page.getByRole("dialog", { name: "Workspace navigation" });
  assert.ok(await workspace.isVisible());
  await page.keyboard.press("Shift+Tab");
  assert.ok(await workspace.evaluate(el => el.contains(document.activeElement)));
  await page.keyboard.press("Escape");
  assert.ok(await page.getByRole("button", { name: "Open workspace menu" }).evaluate(el => el === document.activeElement));
  interactions.workspaceFocusTrap = true;
  const touch = await browser.newContext({ isMobile: true, hasTouch: true, viewport: { width: 390, height: 844 } });
  const touchPage = await touch.newPage(); await touchPage.goto(base + "/jobs"); await touchPage.waitForLoadState("networkidle");
  assert.equal(await touchPage.locator(".glass-interactive").first().evaluate(el => getComputedStyle(el).backdropFilter), "none");
  const save = touchPage.getByRole("button", { name: /^Save job / }).first();
  await save.tap(); await touchPage.getByRole("button", { name: /^Remove saved job / }).first().waitFor(); assert.equal(await touchPage.getByRole("button", { name: /^Remove saved job / }).first().getAttribute("aria-pressed"), "true");
  interactions.touchSave = true;
  await browser.close();
  fs.writeFileSync(path.join(output, "results.json"), JSON.stringify({ checks, errors, interactions }, null, 2));
  assert.equal(errors.length, 0, "Console errors");
  assert.ok(checks.every(r => !r.overflow.length && r.scrollWidth <= r.width), "Viewport overflow");
  console.log(JSON.stringify({ routes: routes.length, viewports: checks.length, errors, interactions, output }));
})().catch(error => { console.error(error); process.exitCode = 1; });

