import { getEmployerDashboard, getEmployerWorkspace, searchCandidates } from "@/features/employer/services/workspace";
import { Lock, MapPin, Search } from "lucide-react";

export const metadata = { title: "Candidate Search | Grow Biz Jobs" };

export default async function EmployerCandidatesPage() {
  const [{ currentEmployerCompany }, data, candidates] = await Promise.all([getEmployerWorkspace(), getEmployerDashboard(), searchCandidates()]);
  const restricted = currentEmployerCompany.verificationStatus !== "verified";
  return <div><h1 className="font-display text-[28px] font-bold text-ink">Candidate Search</h1><p className="mt-2 text-[14.5px] text-mist">Candidate access depends on verification, entitlement and candidate consent. Frontend filtering is not security.</p><div className="mt-5 rounded-card border border-line bg-white p-4 shadow-soft"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex min-h-11 min-w-[220px] flex-1 items-center gap-2.5 rounded-control border border-line px-3"><Search size={16} className="text-mist" aria-hidden="true" /><span className="text-[14px] text-mist">Search candidates</span></div><p className="rounded-pill bg-plum-50 px-3 py-2 text-[13px] font-medium text-plum-700">{data.unlockUsage.used} of {data.unlockUsage.limit} candidate unlocks used</p></div></div>{restricted ? <div className="mt-6 rounded-card border border-line bg-plum-50/60 p-6">Verification required before full candidate search.</div> : <div className="mt-6 grid gap-4 lg:grid-cols-2">{candidates.map((c) => <article key={c.id} className="rounded-card border border-line bg-white p-5 transition-colors hover:border-plum-200"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-[18px] font-semibold text-ink">{c.candidateName.split(" ")[0]} - {c.headline}</h2><p className="mt-1 inline-flex items-center gap-1.5 text-[14px] text-mist">{c.experience} - <MapPin size={14} aria-hidden="true" /> {c.location}</p></div></div><div className="mt-3 flex flex-wrap gap-1.5">{c.tags.map((t) => <span key={t} className="rounded-pill border border-line px-2.5 py-1 text-[12.5px] text-ink/70">{t}</span>)}</div><button className="mt-4 inline-flex min-h-10 items-center gap-1.5 rounded-pill bg-plum-600 px-4 text-[13.5px] font-medium text-white hover:bg-plum-700"><Lock size={13} aria-hidden="true" />Unlock Candidate</button></article>)}</div>}</div>;
}
